In [1]:
import sys, os
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), "..")))
import numpy as np
import nfl_data_py as nfl

In [6]:
data = nfl.import_pbp_data(years=list(range(1999, 2026)))

1999 done.
2000 done.
2001 done.
2002 done.
2003 done.
2004 done.
2005 done.
2006 done.
2007 done.
2008 done.
2009 done.
2010 done.
2011 done.
2012 done.
2013 done.
2014 done.
2015 done.
2016 done.
2017 done.
2018 done.
2019 done.
2020 done.
2021 done.
2022 done.
2023 done.
2024 done.
2025 done.
Downcasting floats.

In [8]:
data["drive"].value_counts()

1.0     60496
6.0     57317
5.0     57128
7.0     56441
4.0     56279
8.0     55709
16.0    55621
3.0     55265
17.0    55212
15.0    54989
2.0     54515
9.0     54309
14.0    53934
18.0    53781
10.0    53547
12.0    53477
13.0    53252
11.0    53017
19.0    51514
20.0    46667
21.0    40982
22.0    34222
23.0    28166
24.0    21985
25.0    16292
26.0    11527
27.0     7471
28.0     4719
29.0     2932
30.0     1774
31.0      907
32.0      509
33.0      312
34.0      204
35.0       90
36.0       63
37.0       40
38.0       25
Name: drive, dtype: int64

In [ ]:
data[(data["game_seconds_remaining"] == 0) & ]["season_type"].value_counts()

REG     7156
POST     302
Name: season_type, dtype: int64

In [ ]:
data[(data["game_date"] < "2024-01-01")& (data["season_type"] == "REG") & data["game_seconds_remaining"] == 0]["game_date"]

200        1999-09-12
380        1999-09-12
556        1999-09-12
745        1999-09-12
944        1999-09-12
              ...
1278185    2026-01-11
1278186    2026-01-11
1278187    2026-01-11
1278188    2026-01-11
1278189    2026-01-11
Name: game_date, Length: 157152, dtype: object

:

In [6]:
data = data[(data["home_team"] == "NYJ") & (data["away_team"] == "BAL")]

In [13]:
data.columns.tolist()

['play_id',
 'game_id',
 'old_game_id',
 'home_team',
 'away_team',
 'season_type',
 'week',
 'posteam',
 'posteam_type',
 'defteam',
 'side_of_field',
 'yardline_100',
 'game_date',
 'quarter_seconds_remaining',
 'half_seconds_remaining',
 'game_seconds_remaining',
 'game_half',
 'quarter_end',
 'drive',
 'sp',
 'qtr',
 'down',
 'goal_to_go',
 'time',
 'yrdln',
 'ydstogo',
 'ydsnet',
 'desc',
 'play_type',
 'yards_gained',
 'shotgun',
 'no_huddle',
 'qb_dropback',
 'qb_kneel',
 'qb_spike',
 'qb_scramble',
 'pass_length',
 'pass_location',
 'air_yards',
 'yards_after_catch',
 'run_location',
 'run_gap',
 'field_goal_result',
 'kick_distance',
 'extra_point_result',
 'two_point_conv_result',
 'home_timeouts_remaining',
 'away_timeouts_remaining',
 'timeout',
 'timeout_team',
 'td_team',
 'td_player_name',
 'td_player_id',
 'posteam_timeouts_remaining',
 'defteam_timeouts_remaining',
 'total_home_score',
 'total_away_score',
 'posteam_score',
 'defteam_score',
 'score_differential',
 'posteam_score_post',
 'defteam_score_post',
 'score_differential_post',
 'no_score_prob',
 'opp_fg_prob',
 'opp_safety_prob',
 'opp_td_prob',
 'fg_prob',
 'safety_prob',
 'td_prob',
 'extra_point_prob',
 'two_point_conversion_prob',
 'ep',
 'epa',
 'total_home_epa',
 'total_away_epa',
 'total_home_rush_epa',
 'total_away_rush_epa',
 'total_home_pass_epa',
 'total_away_pass_epa',
 'air_epa',
 'yac_epa',
 'comp_air_epa',
 'comp_yac_epa',
 'total_home_comp_air_epa',
 'total_away_comp_air_epa',
 'total_home_comp_yac_epa',
 'total_away_comp_yac_epa',
 'total_home_raw_air_epa',
 'total_away_raw_air_epa',
 'total_home_raw_yac_epa',
 'total_away_raw_yac_epa',
 'wp',
 'def_wp',
 'home_wp',
 'away_wp',
 'wpa',
 'vegas_wpa',
 'vegas_home_wpa',
 'home_wp_post',
 'away_wp_post',
 'vegas_wp',
 'vegas_home_wp',
 'total_home_rush_wpa',
 'total_away_rush_wpa',
 'total_home_pass_wpa',
 'total_away_pass_wpa',
 'air_wpa',
 'yac_wpa',
 'comp_air_wpa',
 'comp_yac_wpa',
 'total_home_comp_air_wpa',
 'total_away_comp_air_wpa',
 'total_home_comp_yac_wpa',
 'total_away_comp_yac_wpa',
 'total_home_raw_air_wpa',
 'total_away_raw_air_wpa',
 'total_home_raw_yac_wpa',
 'total_away_raw_yac_wpa',
 'punt_blocked',
 'first_down_rush',
 'first_down_pass',
 'first_down_penalty',
 'third_down_converted',
 'third_down_failed',
 'fourth_down_converted',
 'fourth_down_failed',
 'incomplete_pass',
 'touchback',
 'interception',
 'punt_inside_twenty',
 'punt_in_endzone',
 'punt_out_of_bounds',
 'punt_downed',
 'punt_fair_catch',
 'kickoff_inside_twenty',
 'kickoff_in_endzone',
 'kickoff_out_of_bounds',
 'kickoff_downed',
 'kickoff_fair_catch',
 'fumble_forced',
 'fumble_not_forced',
 'fumble_out_of_bounds',
 'solo_tackle',
 'safety',
 'penalty',
 'tackled_for_loss',
 'fumble_lost',
 'own_kickoff_recovery',
 'own_kickoff_recovery_td',
 'qb_hit',
 'rush_attempt',
 'pass_attempt',
 'sack',
 'touchdown',
 'pass_touchdown',
 'rush_touchdown',
 'return_touchdown',
 'extra_point_attempt',
 'two_point_attempt',
 'field_goal_attempt',
 'kickoff_attempt',
 'punt_attempt',
 'fumble',
 'complete_pass',
 'assist_tackle',
 'lateral_reception',
 'lateral_rush',
 'lateral_return',
 'lateral_recovery',
 'passer_player_id',
 'passer_player_name',
 'passing_yards',
 'receiver_player_id',
 'receiver_player_name',
 'receiving_yards',
 'rusher_player_id',
 'rusher_player_name',
 'rushing_yards',
 'lateral_receiver_player_id',
 'lateral_receiver_player_name',
 'lateral_receiving_yards',
 'lateral_rusher_player_id',
 'lateral_rusher_player_name',
 'lateral_rushing_yards',
 'lateral_sack_player_id',
 'lateral_sack_player_name',
 'interception_player_id',
 'interception_player_name',
 'lateral_interception_player_id',
 'lateral_interception_player_name',
 'punt_returner_player_id',
 'punt_returner_player_name',
 'lateral_punt_returner_player_id',
 'lateral_punt_returner_player_name',
 'kickoff_returner_player_name',
 'kickoff_returner_player_id',
 'lateral_kickoff_returner_player_id',
 'lateral_kickoff_returner_player_name',
 'punter_player_id',
 'punter_player_name',
 'kicker_player_name',
 'kicker_player_id',
 'own_kickoff_recovery_player_id',
 'own_kickoff_recovery_player_name',
 'blocked_player_id',
 'blocked_player_name',
 'tackle_for_loss_1_player_id',
 'tackle_for_loss_1_player_name',
 'tackle_for_loss_2_player_id',
 'tackle_for_loss_2_player_name',
 'qb_hit_1_player_id',
 'qb_hit_1_player_name',
 'qb_hit_2_player_id',
 'qb_hit_2_player_name',
 'forced_fumble_player_1_team',
 'forced_fumble_player_1_player_id',
 'forced_fumble_player_1_player_name',
 'forced_fumble_player_2_team',
 'forced_fumble_player_2_player_id',
 'forced_fumble_player_2_player_name',
 'solo_tackle_1_team',
 'solo_tackle_2_team',
 'solo_tackle_1_player_id',
 'solo_tackle_2_player_id',
 'solo_tackle_1_player_name',
 'solo_tackle_2_player_name',
 'assist_tackle_1_player_id',
 'assist_tackle_1_player_name',
 'assist_tackle_1_team',
 'assist_tackle_2_player_id',
 'assist_tackle_2_player_name',
 'assist_tackle_2_team',
 'assist_tackle_3_player_id',
 'assist_tackle_3_player_name',
 'assist_tackle_3_team',
 'assist_tackle_4_player_id',
 'assist_tackle_4_player_name',
 'assist_tackle_4_team',
 'tackle_with_assist',
 'tackle_with_assist_1_player_id',
 'tackle_with_assist_1_player_name',
 'tackle_with_assist_1_team',
 'tackle_with_assist_2_player_id',
 'tackle_with_assist_2_player_name',
 'tackle_with_assist_2_team',
 'pass_defense_1_player_id',
 'pass_defense_1_player_name',
 'pass_defense_2_player_id',
 'pass_defense_2_player_name',
 'fumbled_1_team',
 'fumbled_1_player_id',
 'fumbled_1_player_name',
 'fumbled_2_player_id',
 'fumbled_2_player_name',
 'fumbled_2_team',
 'fumble_recovery_1_team',
 'fumble_recovery_1_yards',
 'fumble_recovery_1_player_id',
 'fumble_recovery_1_player_name',
 'fumble_recovery_2_team',
 'fumble_recovery_2_yards',
 'fumble_recovery_2_player_id',
 'fumble_recovery_2_player_name',
 'sack_player_id',
 'sack_player_name',
 'half_sack_1_player_id',
 'half_sack_1_player_name',
 'half_sack_2_player_id',
 'half_sack_2_player_name',
 'return_team',
 'return_yards',
 'penalty_team',
 'penalty_player_id',
 'penalty_player_name',
 'penalty_yards',
 'replay_or_challenge',
 'replay_or_challenge_result',
 'penalty_type',
 'defensive_two_point_attempt',
 'defensive_two_point_conv',
 'defensive_extra_point_attempt',
 'defensive_extra_point_conv',
 'safety_player_name',
 'safety_player_id',
 'season',
 'cp',
 'cpoe',
 'series',
 'series_success',
 'series_result',
 'order_sequence',
 'start_time',
 'time_of_day',
 'stadium',
 'weather',
 'nfl_api_id',
 'play_clock',
 'play_deleted',
 'play_type_nfl',
 'special_teams_play',
 'st_play_type',
 'end_clock_time',
 'end_yard_line',
 'fixed_drive',
 'fixed_drive_result',
 'drive_real_start_time',
 'drive_play_count',
 'drive_time_of_possession',
 'drive_first_downs',
 'drive_inside20',
 'drive_ended_with_score',
 'drive_quarter_start',
 'drive_quarter_end',
 'drive_yards_penalized',
 'drive_start_transition',
 'drive_end_transition',
 'drive_game_clock_start',
 'drive_game_clock_end',
 'drive_start_yard_line',
 'drive_end_yard_line',
 'drive_play_id_started',
 'drive_play_id_ended',
 'away_score',
 'home_score',
 'location',
 'result',
 'total',
 'spread_line',
 'total_line',
 'div_game',
 'roof',
 'surface',
 'temp',
 'wind',
 'home_coach',
 'away_coach',
 'stadium_id',
 'game_stadium',
 'aborted_play',
 'success',
 'passer',
 'passer_jersey_number',
 'rusher',
 'rusher_jersey_number',
 'receiver',
 'receiver_jersey_number',
 'pass',
 'rush',
 'first_down',
 'special',
 'play',
 'passer_id',
 'rusher_id',
 'receiver_id',
 'name',
 'jersey_number',
 'id',
 'fantasy_player_name',
 'fantasy_player_id',
 'fantasy',
 'fantasy_id',
 'out_of_bounds',
 'home_opening_kickoff',
 'qb_epa',
 'xyac_epa',
 'xyac_mean_yardage',
 'xyac_median_yardage',
 'xyac_success',
 'xyac_fd',
 'xpass',
 'pass_oe',
 'old_game_id_x',
 'nflverse_game_id',
 'old_game_id_y',
 'possession_team',
 'offense_formation',
 'offense_personnel',
 'defenders_in_box',
 'defense_personnel',
 'number_of_pass_rushers',
 'players_on_play',
 'offense_players',
 'defense_players',
 'n_offense',
 'n_defense',
 'ngs_air_yards',
 'time_to_throw',
 'was_pressure',
 'route',
 'defense_man_zone_type',
 'defense_coverage_type',
 'offense_names',
 'defense_names',
 'offense_positions',
 'defense_positions',
 'offense_numbers',
 'defense_numbers']

In [8]:
data["first_down_rush"].value_counts()

0.0    165
1.0      7
Name: first_down_rush, dtype: int64

In [9]:
for i in data.columns:
    print(i)

play_id
game_id
old_game_id_x
home_team
away_team
season_type
week
posteam
posteam_type
defteam
side_of_field
yardline_100
game_date
quarter_seconds_remaining
half_seconds_remaining
game_seconds_remaining
game_half
quarter_end
drive
sp
qtr
down
goal_to_go
time
yrdln
ydstogo
ydsnet
desc
play_type
yards_gained
shotgun
no_huddle
qb_dropback
qb_kneel
qb_spike
qb_scramble
pass_length
pass_location
air_yards
yards_after_catch
run_location
run_gap
field_goal_result
kick_distance
extra_point_result
two_point_conv_result
home_timeouts_remaining
away_timeouts_remaining
timeout
timeout_team
td_team
td_player_name
td_player_id
posteam_timeouts_remaining
defteam_timeouts_remaining
total_home_score
total_away_score
posteam_score
defteam_score
score_differential
posteam_score_post
defteam_score_post
score_differential_post
no_score_prob
opp_fg_prob
opp_safety_prob
opp_td_prob
fg_prob
safety_prob
td_prob
extra_point_prob
two_point_conversion_prob
ep
epa
total_home_epa
total_away_epa
total_home_rush_epa
total_away_rush_epa
total_home_pass_epa
total_away_pass_epa
air_epa
yac_epa
comp_air_epa
comp_yac_epa
total_home_comp_air_epa
total_away_comp_air_epa
total_home_comp_yac_epa
total_away_comp_yac_epa
total_home_raw_air_epa
total_away_raw_air_epa
total_home_raw_yac_epa
total_away_raw_yac_epa
wp
def_wp
home_wp
away_wp
wpa
vegas_wpa
vegas_home_wpa
home_wp_post
away_wp_post
vegas_wp
vegas_home_wp
total_home_rush_wpa
total_away_rush_wpa
total_home_pass_wpa
total_away_pass_wpa
air_wpa
yac_wpa
comp_air_wpa
comp_yac_wpa
total_home_comp_air_wpa
total_away_comp_air_wpa
total_home_comp_yac_wpa
total_away_comp_yac_wpa
total_home_raw_air_wpa
total_away_raw_air_wpa
total_home_raw_yac_wpa
total_away_raw_yac_wpa
punt_blocked
first_down_rush
first_down_pass
first_down_penalty
third_down_converted
third_down_failed
fourth_down_converted
fourth_down_failed
incomplete_pass
touchback
interception
punt_inside_twenty
punt_in_endzone
punt_out_of_bounds
punt_downed
punt_fair_catch
kickoff_inside_twenty
kickoff_in_endzone
kickoff_out_of_bounds
kickoff_downed
kickoff_fair_catch
fumble_forced
fumble_not_forced
fumble_out_of_bounds
solo_tackle
safety
penalty
tackled_for_loss
fumble_lost
own_kickoff_recovery
own_kickoff_recovery_td
qb_hit
rush_attempt
pass_attempt
sack
touchdown
pass_touchdown
rush_touchdown
return_touchdown
extra_point_attempt
two_point_attempt
field_goal_attempt
kickoff_attempt
punt_attempt
fumble
complete_pass
assist_tackle
lateral_reception
lateral_rush
lateral_return
lateral_recovery
passer_player_id
passer_player_name
passing_yards
receiver_player_id
receiver_player_name
receiving_yards
rusher_player_id
rusher_player_name
rushing_yards
lateral_receiver_player_id
lateral_receiver_player_name
lateral_receiving_yards
lateral_rusher_player_id
lateral_rusher_player_name
lateral_rushing_yards
lateral_sack_player_id
lateral_sack_player_name
interception_player_id
interception_player_name
lateral_interception_player_id
lateral_interception_player_name
punt_returner_player_id
punt_returner_player_name
lateral_punt_returner_player_id
lateral_punt_returner_player_name
kickoff_returner_player_name
kickoff_returner_player_id
lateral_kickoff_returner_player_id
lateral_kickoff_returner_player_name
punter_player_id
punter_player_name
kicker_player_name
kicker_player_id
own_kickoff_recovery_player_id
own_kickoff_recovery_player_name
blocked_player_id
blocked_player_name
tackle_for_loss_1_player_id
tackle_for_loss_1_player_name
tackle_for_loss_2_player_id
tackle_for_loss_2_player_name
qb_hit_1_player_id
qb_hit_1_player_name
qb_hit_2_player_id
qb_hit_2_player_name
forced_fumble_player_1_team
forced_fumble_player_1_player_id
forced_fumble_player_1_player_name
forced_fumble_player_2_team
forced_fumble_player_2_player_id
forced_fumble_player_2_player_name
solo_tackle_1_team
solo_tackle_2_team
solo_tackle_1_player_id
solo_tackle_2_player_id
solo_tackle_1_player_name
solo_tackle_2_player_name
assist_tackle_1_player_id
assist_tackle_1_player_name
assist_tackle_1_team
assist_tackle_2_player_id
assist_tackle_2_player_name
assist_tackle_2_team
assist_tackle_3_player_id
assist_tackle_3_player_name
assist_tackle_3_team
assist_tackle_4_player_id
assist_tackle_4_player_name
assist_tackle_4_team
tackle_with_assist
tackle_with_assist_1_player_id
tackle_with_assist_1_player_name
tackle_with_assist_1_team
tackle_with_assist_2_player_id
tackle_with_assist_2_player_name
tackle_with_assist_2_team
pass_defense_1_player_id
pass_defense_1_player_name
pass_defense_2_player_id
pass_defense_2_player_name
fumbled_1_team
fumbled_1_player_id
fumbled_1_player_name
fumbled_2_player_id
fumbled_2_player_name
fumbled_2_team
fumble_recovery_1_team
fumble_recovery_1_yards
fumble_recovery_1_player_id
fumble_recovery_1_player_name
fumble_recovery_2_team
fumble_recovery_2_yards
fumble_recovery_2_player_id
fumble_recovery_2_player_name
sack_player_id
sack_player_name
half_sack_1_player_id
half_sack_1_player_name
half_sack_2_player_id
half_sack_2_player_name
return_team
return_yards
penalty_team
penalty_player_id
penalty_player_name
penalty_yards
replay_or_challenge
replay_or_challenge_result
penalty_type
defensive_two_point_attempt
defensive_two_point_conv
defensive_extra_point_attempt
defensive_extra_point_conv
safety_player_name
safety_player_id
season
cp
cpoe
series
series_success
series_result
order_sequence
start_time
time_of_day
stadium
weather
nfl_api_id
play_clock
play_deleted
play_type_nfl
special_teams_play
st_play_type
end_clock_time
end_yard_line
fixed_drive
fixed_drive_result
drive_real_start_time
drive_play_count
drive_time_of_possession
drive_first_downs
drive_inside20
drive_ended_with_score
drive_quarter_start
drive_quarter_end
drive_yards_penalized
drive_start_transition
drive_end_transition
drive_game_clock_start
drive_game_clock_end
drive_start_yard_line
drive_end_yard_line
drive_play_id_started
drive_play_id_ended
away_score
home_score
location
result
total
spread_line
total_line
div_game
roof
surface
temp
wind
home_coach
away_coach
stadium_id
game_stadium
aborted_play
success
passer
passer_jersey_number
rusher
rusher_jersey_number
receiver
receiver_jersey_number
pass
rush
first_down
special
play
passer_id
rusher_id
receiver_id
name
jersey_number
id
fantasy_player_name
fantasy_player_id
fantasy
fantasy_id
out_of_bounds
home_opening_kickoff
qb_epa
xyac_epa
xyac_mean_yardage
xyac_median_yardage
xyac_success
xyac_fd
xpass
pass_oe
nflverse_game_id
old_game_id_y
possession_team
offense_formation
offense_personnel
defenders_in_box
defense_personnel
number_of_pass_rushers
players_on_play
offense_players
defense_players
n_offense
n_defense
ngs_air_yards
time_to_throw
was_pressure
route
defense_man_zone_type
defense_coverage_type

In [23]:
data[["posteam_type"]].value_counts()

posteam_type
home            99
away            71
dtype: int64

In [25]:
data["down"].value_counts()

1.0    61
2.0    44
3.0    30
4.0    20
Name: down, dtype: int64

In [12]:
data["sack"].value_counts()

0.0    167
1.0      5
Name: sack, dtype: int64

In [13]:
data["penalty_yards"].value_counts()

10.0    5
5.0     3
32.0    1
9.0     1
4.0     1
Name: penalty_yards, dtype: int64

In [14]:
data

,play_id,game_id,old_game_id_x,home_team,away_team,season_type,week,posteam,posteam_type,defteam,...,offense_players,defense_players,n_offense,n_defense,ngs_air_yards,time_to_throw,was_pressure,route,defense_man_zone_type,defense_coverage_type
0,1.0,2022_01_BAL_NYJ,2022091107,NYJ,BAL,REG,1,None,None,None,...,,,0,0,NaN,NaN,None,None,None,None
1,43.0,2022_01_BAL_NYJ,2022091107,NYJ,BAL,REG,1,NYJ,home,BAL,...,00-0036157;00-0035202;00-0037984;00-0029597;00...,00-0035537;00-0032134;00-0034419;00-0036500;00...,11,11,NaN,NaN,None,None,None,None
2,68.0,2022_01_BAL_NYJ,2022091107,NYJ,BAL,REG,1,NYJ,home,BAL,...,00-0036924;00-0032466;00-0036979;00-0032234;00...,00-0033294;00-0026190;00-0032574;00-0028278;00...,11,11,NaN,NaN,None,None,None,None
3,89.0,2022_01_BAL_NYJ,2022091107,NYJ,BAL,REG,1,NYJ,home,BAL,...,00-0036924;00-0032466;00-0032234;00-0036979;00...,00-0033294;00-0026190;00-0032574;00-0028278;00...,11,11,0.56,3.07,True,ANGLE,ZONE_COVERAGE,COVER_2
4,115.0,2022_01_BAL_NYJ,2022091107,NYJ,BAL,REG,1,NYJ,home,BAL,...,00-0036924;00-0032466;00-0036979;00-0032234;00...,00-0033294;00-0026190;00-0032574;00-0028278;00...,11,11,NaN,NaN,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172,4135.0,2022_01_BAL_NYJ,2022091107,NYJ,BAL,REG,1,NYJ,home,BAL,...,00-0032466;00-0036979;00-0032234;00-0032134;00...,00-0036081;00-0036157;00-0033294;00-0026190;00...,11,11,NaN,NaN,None,None,None,None
173,4151.0,2022_01_BAL_NYJ,2022091107,NYJ,BAL,REG,1,BAL,away,NYJ,...,00-0036500;00-0034730;00-0036501;00-0033770;00...,00-0036133;00-0036157;00-0033294;00-0034753;00...,11,11,NaN,NaN,None,None,None,None
174,4171.0,2022_01_BAL_NYJ,2022091107,NYJ,BAL,REG,1,BAL,away,NYJ,...,00-0033118;00-0034978;00-0035249;00-0037838;00...,00-0034384;00-0032109;00-0032759;00-0037190;00...,11,11,NaN,NaN,None,None,None,None
175,4200.0,2022_01_BAL_NYJ,2022091107,NYJ,BAL,REG,1,BAL,away,NYJ,...,00-0034978;00-0033118;00-0035249;00-0037838;00...,00-0034384;00-0032109;00-0037190;00-0032759;00...,11,11,NaN,NaN,None,None,None,None
176,4221.0,2022_01_BAL_NYJ,2022091107,NYJ,BAL,REG,1,BAL,away,NYJ,...,,,0,0,NaN,NaN,None,None,None,None

In [15]:
for i in data[["passing_yards", "posteam"]].itertuples():
    print(i.passing_yards, i.posteam)

nan None
nan NYJ
nan NYJ
nan NYJ
nan NYJ
nan NYJ
nan NYJ
4.0 BAL
4.0 BAL
nan BAL
nan BAL
8.0 BAL
nan BAL
nan None
nan BAL
nan NYJ
3.0 NYJ
nan NYJ
nan NYJ
nan NYJ
nan NYJ
nan NYJ
nan BAL
nan BAL
nan BAL
nan BAL
24.0 NYJ
nan NYJ
nan NYJ
nan BAL
8.0 BAL
nan BAL
nan BAL
nan NYJ
nan NYJ
nan NYJ
9.0 NYJ
nan NYJ
11.0 BAL
2.0 BAL
nan BAL
nan BAL
nan BAL
nan BAL
15.0 NYJ
11.0 NYJ
nan NYJ
8.0 NYJ
nan NYJ
6.0 NYJ
nan NYJ
nan NYJ
5.0 BAL
11.0 BAL
nan BAL
nan BAL
nan BAL
nan BAL
nan NYJ
5.0 NYJ
6.0 NYJ
nan NYJ
nan NYJ
nan NYJ
nan NYJ
nan BAL
nan BAL
5.0 BAL
25.0 BAL
nan BAL
nan NYJ
nan NYJ
nan NYJ
3.0 NYJ
13.0 NYJ
nan NYJ
nan None
nan NYJ
nan None
2.0 NYJ
nan None
nan NYJ
nan BAL
nan BAL
nan None
nan BAL
nan BAL
nan BAL
nan BAL
nan BAL
nan BAL
nan BAL
nan BAL
nan NYJ
0.0 NYJ
9.0 NYJ
nan NYJ
15.0 BAL
nan BAL
nan BAL
nan BAL
nan BAL
17.0 BAL
nan BAL
nan NYJ
nan NYJ
nan NYJ
nan NYJ
nan NYJ
nan NYJ
nan NYJ
nan NYJ
nan BAL
15.0 BAL
nan BAL
nan BAL
55.0 BAL
nan BAL
nan NYJ
17.0 NYJ
8.0 NYJ
2.0 NYJ
nan NYJ
12.0 NYJ
12.0 NYJ
nan NYJ
15.0 NYJ
3.0 NYJ
6.0 NYJ
nan BAL
nan BAL
4.0 BAL
17.0 BAL
nan BAL
nan BAL
nan BAL
nan BAL
17.0 NYJ
nan NYJ
6.0 NYJ
8.0 NYJ
nan NYJ
9.0 NYJ
nan NYJ
7.0 NYJ
nan NYJ
9.0 NYJ
5.0 NYJ
3.0 NYJ
4.0 NYJ
nan NYJ
4.0 NYJ
nan NYJ
nan NYJ
nan BAL
nan None
7.0 BAL
nan BAL
nan BAL
nan NYJ
16.0 NYJ
5.0 NYJ
nan NYJ
nan NYJ
5.0 NYJ
nan NYJ
nan NYJ
nan NYJ
19.0 NYJ
nan NYJ
nan NYJ
3.0 NYJ
nan NYJ
nan BAL
nan BAL
nan BAL
nan BAL

In [16]:
data["passing_yards"].describe()

count    54.000000
mean      9.666667
std       8.518570
min       0.000000
25%       4.250000
50%       8.000000
75%      12.750000
max      55.000000
Name: passing_yards, dtype: float64

In [17]:
data["interception"]

0      NaN
1      0.0
2      0.0
3      0.0
4      0.0
      ...
172    0.0
173    0.0
174    0.0
175    0.0
176    NaN
Name: interception, Length: 177, dtype: float32

In [35]:
data["rush_touchdown"].value_counts()

0.0    172
Name: rush_touchdown, dtype: int64

In [42]:
data["tackled_for_loss"].value_counts()

0.0    169
1.0      3
Name: tackled_for_loss, dtype: int64

In [59]:
data["kickoff_attempt"]

0      NaN
1      1.0
2      0.0
3      0.0
4      0.0
      ...
172    0.0
173    1.0
174    0.0
175    0.0
176    NaN
Name: kickoff_attempt, Length: 177, dtype: float32

In [34]:
features = [
        "game_id","season","week","season_type","game_date",
        "stadium","game_stadium","roof","surface","location","temp","wind",
        "home_team","away_team","home_coach","away_coach","div_game",
        "home_score","away_score","total_home_score","total_away_score",
        "posteam_score","defteam_score","score_differential",
        "first_down_rush","first_down_pass","third_down_converted","fourth_down_converted",
        "sack","interception","fumble_lost","fumble_forced","penalty_yards",
        "rush_attempt","pass_attempt","rushing_yards","passing_yards","receiving_yards",
        "pass_touchdown","qb_dropback","rush_touchdown","yards_after_catch",
        "tackled_for_loss","qb_hit","fumble_recovery_1_yards",
        "field_goal_attempt","field_goal_result","extra_point_attempt","extra_point_result",
        "punt_attempt","kickoff_attempt","kickoff_inside_twenty","punt_yards",
        "spread_line","total_line","vegas_wp","vegas_home_wp",
        "total_home_epa","total_away_epa","total_home_rush_epa","total_away_rush_epa",
        "total_home_pass_epa","total_away_pass_epa",
        "total_home_comp_air_epa","total_away_comp_air_epa",
        "total_home_comp_yac_epa","total_away_comp_yac_epa",
        "total_home_raw_air_epa","total_away_raw_air_epa",
        "total_home_raw_yac_epa","total_away_raw_yac_epa",
        "total_home_comp_air_wpa","total_away_comp_air_wpa",
        "total_home_comp_yac_wpa","total_away_comp_yac_wpa",
        "total_home_raw_air_wpa","total_away_raw_air_wpa",
        "total_home_raw_yac_wpa","total_away_raw_yac_wpa",
        "quarter_seconds_remaining", "half_seconds_remaining",
        "game_seconds_remaining", "game_half", "quarter_end"
    ]


print(len(features))
count = 0
for i in data.columns:
    if i not in features:
        count += 1
print(count)

84
308

In [35]:
import nfl_data_py as nfl
df = nfl.import_pbp_data([2023], downcast=True)
print(df.columns.tolist())

2023 done.
Downcasting floats.
['play_id', 'game_id', 'old_game_id_x', 'home_team', 'away_team', 'season_type', 'week', 'posteam', 'posteam_type', 'defteam', 'side_of_field', 'yardline_100', 'game_date', 'quarter_seconds_remaining', 'half_seconds_remaining', 'game_seconds_remaining', 'game_half', 'quarter_end', 'drive', 'sp', 'qtr', 'down', 'goal_to_go', 'time', 'yrdln', 'ydstogo', 'ydsnet', 'desc', 'play_type', 'yards_gained', 'shotgun', 'no_huddle', 'qb_dropback', 'qb_kneel', 'qb_spike', 'qb_scramble', 'pass_length', 'pass_location', 'air_yards', 'yards_after_catch', 'run_location', 'run_gap', 'field_goal_result', 'kick_distance', 'extra_point_result', 'two_point_conv_result', 'home_timeouts_remaining', 'away_timeouts_remaining', 'timeout', 'timeout_team', 'td_team', 'td_player_name', 'td_player_id', 'posteam_timeouts_remaining', 'defteam_timeouts_remaining', 'total_home_score', 'total_away_score', 'posteam_score', 'defteam_score', 'score_differential', 'posteam_score_post', 'defteam_score_post', 'score_differential_post', 'no_score_prob', 'opp_fg_prob', 'opp_safety_prob', 'opp_td_prob', 'fg_prob', 'safety_prob', 'td_prob', 'extra_point_prob', 'two_point_conversion_prob', 'ep', 'epa', 'total_home_epa', 'total_away_epa', 'total_home_rush_epa', 'total_away_rush_epa', 'total_home_pass_epa', 'total_away_pass_epa', 'air_epa', 'yac_epa', 'comp_air_epa', 'comp_yac_epa', 'total_home_comp_air_epa', 'total_away_comp_air_epa', 'total_home_comp_yac_epa', 'total_away_comp_yac_epa', 'total_home_raw_air_epa', 'total_away_raw_air_epa', 'total_home_raw_yac_epa', 'total_away_raw_yac_epa', 'wp', 'def_wp', 'home_wp', 'away_wp', 'wpa', 'vegas_wpa', 'vegas_home_wpa', 'home_wp_post', 'away_wp_post', 'vegas_wp', 'vegas_home_wp', 'total_home_rush_wpa', 'total_away_rush_wpa', 'total_home_pass_wpa', 'total_away_pass_wpa', 'air_wpa', 'yac_wpa', 'comp_air_wpa', 'comp_yac_wpa', 'total_home_comp_air_wpa', 'total_away_comp_air_wpa', 'total_home_comp_yac_wpa', 'total_away_comp_yac_wpa', 'total_home_raw_air_wpa', 'total_away_raw_air_wpa', 'total_home_raw_yac_wpa', 'total_away_raw_yac_wpa', 'punt_blocked', 'first_down_rush', 'first_down_pass', 'first_down_penalty', 'third_down_converted', 'third_down_failed', 'fourth_down_converted', 'fourth_down_failed', 'incomplete_pass', 'touchback', 'interception', 'punt_inside_twenty', 'punt_in_endzone', 'punt_out_of_bounds', 'punt_downed', 'punt_fair_catch', 'kickoff_inside_twenty', 'kickoff_in_endzone', 'kickoff_out_of_bounds', 'kickoff_downed', 'kickoff_fair_catch', 'fumble_forced', 'fumble_not_forced', 'fumble_out_of_bounds', 'solo_tackle', 'safety', 'penalty', 'tackled_for_loss', 'fumble_lost', 'own_kickoff_recovery', 'own_kickoff_recovery_td', 'qb_hit', 'rush_attempt', 'pass_attempt', 'sack', 'touchdown', 'pass_touchdown', 'rush_touchdown', 'return_touchdown', 'extra_point_attempt', 'two_point_attempt', 'field_goal_attempt', 'kickoff_attempt', 'punt_attempt', 'fumble', 'complete_pass', 'assist_tackle', 'lateral_reception', 'lateral_rush', 'lateral_return', 'lateral_recovery', 'passer_player_id', 'passer_player_name', 'passing_yards', 'receiver_player_id', 'receiver_player_name', 'receiving_yards', 'rusher_player_id', 'rusher_player_name', 'rushing_yards', 'lateral_receiver_player_id', 'lateral_receiver_player_name', 'lateral_receiving_yards', 'lateral_rusher_player_id', 'lateral_rusher_player_name', 'lateral_rushing_yards', 'lateral_sack_player_id', 'lateral_sack_player_name', 'interception_player_id', 'interception_player_name', 'lateral_interception_player_id', 'lateral_interception_player_name', 'punt_returner_player_id', 'punt_returner_player_name', 'lateral_punt_returner_player_id', 'lateral_punt_returner_player_name', 'kickoff_returner_player_name', 'kickoff_returner_player_id', 'lateral_kickoff_returner_player_id', 'lateral_kickoff_returner_player_name', 'punter_player_id', 'punter_player_name', 'kicker_player_name', 'kicker_player_id', 'own_kickoff_recovery_player_id', 'own_kickoff_recovery_player_name', 'blocked_player_id', 'blocked_player_name', 'tackle_for_loss_1_player_id', 'tackle_for_loss_1_player_name', 'tackle_for_loss_2_player_id', 'tackle_for_loss_2_player_name', 'qb_hit_1_player_id', 'qb_hit_1_player_name', 'qb_hit_2_player_id', 'qb_hit_2_player_name', 'forced_fumble_player_1_team', 'forced_fumble_player_1_player_id', 'forced_fumble_player_1_player_name', 'forced_fumble_player_2_team', 'forced_fumble_player_2_player_id', 'forced_fumble_player_2_player_name', 'solo_tackle_1_team', 'solo_tackle_2_team', 'solo_tackle_1_player_id', 'solo_tackle_2_player_id', 'solo_tackle_1_player_name', 'solo_tackle_2_player_name', 'assist_tackle_1_player_id', 'assist_tackle_1_player_name', 'assist_tackle_1_team', 'assist_tackle_2_player_id', 'assist_tackle_2_player_name', 'assist_tackle_2_team', 'assist_tackle_3_player_id', 'assist_tackle_3_player_name', 'assist_tackle_3_team', 'assist_tackle_4_player_id', 'assist_tackle_4_player_name', 'assist_tackle_4_team', 'tackle_with_assist', 'tackle_with_assist_1_player_id', 'tackle_with_assist_1_player_name', 'tackle_with_assist_1_team', 'tackle_with_assist_2_player_id', 'tackle_with_assist_2_player_name', 'tackle_with_assist_2_team', 'pass_defense_1_player_id', 'pass_defense_1_player_name', 'pass_defense_2_player_id', 'pass_defense_2_player_name', 'fumbled_1_team', 'fumbled_1_player_id', 'fumbled_1_player_name', 'fumbled_2_player_id', 'fumbled_2_player_name', 'fumbled_2_team', 'fumble_recovery_1_team', 'fumble_recovery_1_yards', 'fumble_recovery_1_player_id', 'fumble_recovery_1_player_name', 'fumble_recovery_2_team', 'fumble_recovery_2_yards', 'fumble_recovery_2_player_id', 'fumble_recovery_2_player_name', 'sack_player_id', 'sack_player_name', 'half_sack_1_player_id', 'half_sack_1_player_name', 'half_sack_2_player_id', 'half_sack_2_player_name', 'return_team', 'return_yards', 'penalty_team', 'penalty_player_id', 'penalty_player_name', 'penalty_yards', 'replay_or_challenge', 'replay_or_challenge_result', 'penalty_type', 'defensive_two_point_attempt', 'defensive_two_point_conv', 'defensive_extra_point_attempt', 'defensive_extra_point_conv', 'safety_player_name', 'safety_player_id', 'season', 'cp', 'cpoe', 'series', 'series_success', 'series_result', 'order_sequence', 'start_time', 'time_of_day', 'stadium', 'weather', 'nfl_api_id', 'play_clock', 'play_deleted', 'play_type_nfl', 'special_teams_play', 'st_play_type', 'end_clock_time', 'end_yard_line', 'fixed_drive', 'fixed_drive_result', 'drive_real_start_time', 'drive_play_count', 'drive_time_of_possession', 'drive_first_downs', 'drive_inside20', 'drive_ended_with_score', 'drive_quarter_start', 'drive_quarter_end', 'drive_yards_penalized', 'drive_start_transition', 'drive_end_transition', 'drive_game_clock_start', 'drive_game_clock_end', 'drive_start_yard_line', 'drive_end_yard_line', 'drive_play_id_started', 'drive_play_id_ended', 'away_score', 'home_score', 'location', 'result', 'total', 'spread_line', 'total_line', 'div_game', 'roof', 'surface', 'temp', 'wind', 'home_coach', 'away_coach', 'stadium_id', 'game_stadium', 'aborted_play', 'success', 'passer', 'passer_jersey_number', 'rusher', 'rusher_jersey_number', 'receiver', 'receiver_jersey_number', 'pass', 'rush', 'first_down', 'special', 'play', 'passer_id', 'rusher_id', 'receiver_id', 'name', 'jersey_number', 'id', 'fantasy_player_name', 'fantasy_player_id', 'fantasy', 'fantasy_id', 'out_of_bounds', 'home_opening_kickoff', 'qb_epa', 'xyac_epa', 'xyac_mean_yardage', 'xyac_median_yardage', 'xyac_success', 'xyac_fd', 'xpass', 'pass_oe', 'nflverse_game_id', 'old_game_id_y', 'possession_team', 'offense_formation', 'offense_personnel', 'defenders_in_box', 'defense_personnel', 'number_of_pass_rushers', 'players_on_play', 'offense_players', 'defense_players', 'n_offense', 'n_defense', 'ngs_air_yards', 'time_to_throw', 'was_pressure', 'route', 'defense_man_zone_type', 'defense_coverage_type', 'offense_names', 'defense_names', 'offense_positions', 'defense_positions', 'offense_numbers', 'defense_numbers']

In [36]:
for i in features:
    if i not in df.columns.to_list():
        print(i)

punt_yards

In [11]:
import requests
from functools import lru_cache

@lru_cache(maxsize=32)
def get_coach_name(team_id, year):
    """
    Fetch head coach's first and last name for a given team ID and season.
    """
    url = f"https://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/{year}/teams/{team_id}/coaches"
    resp = requests.get(url).json()
    
    # Get the first coach's detail (usually head coach)
    coach_details = requests.get(resp["items"][0]["$ref"]).json()
    return coach_details.get("firstName"), coach_details.get("lastName")


def get_team_details(year: int, week: int):
    """
    Fetch NFL schedule details including:
    - home team abbreviation
    - away team abbreviation
    - head coach first and last name
    - stadium
    """
    url = f"https://cdn.espn.com/core/nfl/schedule?xhr=1&year={year}&week={week}"
    response = requests.get(url)
    data = response.json()

    games = []
    schedule = data.get("content", {}).get("schedule", {})

    for date_key, date_data in schedule.items():
        for game in date_data.get("games", []):
            comp = game["competitions"][0]
            teams = comp["competitors"]

            home = next((t for t in teams if t.get("homeAway") == "home"), None)
            away = next((t for t in teams if t.get("homeAway") == "away"), None)
            if not home or not away:
                continue

            home_abbr = home["team"].get("abbreviation")
            away_abbr = away["team"].get("abbreviation")
            stadium = comp.get("venue", {}).get("fullName")

            home_id = home["team"].get("id")
            away_id = away["team"].get("id")

            # Fetch head coach names
            home_first, home_last = get_coach_name(home_id, year)
            away_first, away_last = get_coach_name(away_id, year)

            games.append({
                "home_team": home_abbr,
                "home_coach": f"{home_first} {home_last}",
                "away_team": away_abbr,
                "away_coach": f"{away_first} {away_last}",
                "stadium": stadium
            })

    return games

In [12]:
get_team_details(2025, 3)

[{'home_team': 'BUF',
  'home_coach': 'Sean McDermott',
  'away_team': 'MIA',
  'away_coach': 'Mike McDaniel',
  'stadium': 'Highmark Stadium'},
 {'home_team': 'CLE',
  'home_coach': 'Kevin Stefanski',
  'away_team': 'GB',
  'away_coach': 'Matt LaFleur',
  'stadium': 'Huntington Bank Field'},
 {'home_team': 'TEN',
  'home_coach': 'Brian Callahan',
  'away_team': 'IND',
  'away_coach': 'Shane Steichen',
  'stadium': 'Nissan Stadium'},
 {'home_team': 'MIN',
  'home_coach': "Kevin O'Connell",
  'away_team': 'CIN',
  'away_coach': 'Zac Taylor',
  'stadium': 'U.S. Bank Stadium'},
 {'home_team': 'NE',
  'home_coach': 'Mike Vrabel',
  'away_team': 'PIT',
  'away_coach': 'Mike Tomlin',
  'stadium': 'Gillette Stadium'},
 {'home_team': 'PHI',
  'home_coach': 'Nick Sirianni',
  'away_team': 'LAR',
  'away_coach': 'Sean McVay',
  'stadium': 'Lincoln Financial Field'},
 {'home_team': 'TB',
  'home_coach': 'Todd Bowles',
  'away_team': 'NYJ',
  'away_coach': 'Aaron Glenn',
  'stadium': 'Raymond James Stadium'},
 {'home_team': 'WSH',
  'home_coach': 'Dan Quinn',
  'away_team': 'LV',
  'away_coach': 'Pete Carroll',
  'stadium': 'Northwest Stadium'},
 {'home_team': 'CAR',
  'home_coach': 'Dave Canales',
  'away_team': 'ATL',
  'away_coach': 'Raheem Morris',
  'stadium': 'Bank of America Stadium'},
 {'home_team': 'JAX',
  'home_coach': 'Liam Coen',
  'away_team': 'HOU',
  'away_coach': 'DeMeco Ryans',
  'stadium': 'EverBank Stadium'},
 {'home_team': 'LAC',
  'home_coach': 'Jim Harbaugh',
  'away_team': 'DEN',
  'away_coach': 'Sean Payton',
  'stadium': 'SoFi Stadium'},
 {'home_team': 'SEA',
  'home_coach': 'Mike Macdonald',
  'away_team': 'NO',
  'away_coach': 'Kellen Moore',
  'stadium': 'Lumen Field'},
 {'home_team': 'CHI',
  'home_coach': 'Ben Johnson',
  'away_team': 'DAL',
  'away_coach': 'Brian Schottenheimer',
  'stadium': 'Soldier Field'},
 {'home_team': 'SF',
  'home_coach': 'Kyle Shanahan',
  'away_team': 'ARI',
  'away_coach': 'Jonathan Gannon',
  'stadium': "Levi's Stadium"},
 {'home_team': 'NYG',
  'home_coach': 'Brian Daboll',
  'away_team': 'KC',
  'away_coach': 'Andy Reid',
  'stadium': 'MetLife Stadium'},
 {'home_team': 'BAL',
  'home_coach': 'John Harbaugh',
  'away_team': 'DET',
  'away_coach': 'Dan Campbell',
  'stadium': 'M&T Bank Stadium'}]

In [1]:
import requests

def get_match_winner(event_id):
    """Fetch the winning team's abbreviation for a given NFL event ID from ESPN's API."""
    base_url = f"https://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/{event_id}"
    
    # Get event data
    event_response = requests.get(base_url)
    event_data = event_response.json()
    
    # Get competition details
    competition_url = event_data.get("competitions", [])[0]["$ref"]
    competition_data = requests.get(competition_url).json()
    
    # Get list of competitors
    competitors = competition_data["competitors"]
    
    winner_team_abbr = None
    
    # Loop through competitors to find the winner
    for team_info in competitors:
        team_data = requests.get(team_info["$ref"]).json()
        if team_data.get("winner", False):
            # Fetch team details (to get abbreviation)
            team_url = team_data["team"]["$ref"]
            team_details = requests.get(team_url).json()
            winner_team_abbr = team_details["abbreviation"]
            break
    
    return winner_team_abbr

# Example
print(get_match_winner("401772937"))

BUF

In [11]:
import requests
from functools import lru_cache
from typing import Optional, Tuple, List, Dict, Any


@lru_cache(maxsize=32)
def get_coach_name(team_id: str, year: int) -> Tuple[Optional[str], Optional[str]]:
    """
    Fetch head coach's first and last name for a given team ID and season.
    Returns:
        (first_name, last_name) or (None, None) if not found.
    """
    url = f"https://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/{year}/teams/{team_id}/coaches"
    resp = requests.get(url).json()

    # Defensive coding: handle missing or malformed data
    try:
        coach_details = requests.get(resp["items"][0]["$ref"]).json()
        return coach_details.get("firstName"), coach_details.get("lastName")
    except (KeyError, IndexError, requests.RequestException):
        return None, None


def get_team_logo(team_id: str, year: int) -> Optional[str]:
    """
    Fetch team logo URL from ESPN team API.
    Args:
        team_id (str): Team ID
        year (int): Season year
    Returns:
        str | None: Team logo URL if available, else None
    """
    try:
        url = f"http://sports.core.api.espn.com/v2/sports/football/leagues/nfl/seasons/{year}/teams/{team_id}?lang=en&region=us"
        response = requests.get(url)
        data = response.json()

        logos = data.get("logos", [])
        if logos and isinstance(logos, list):
            return logos[0].get("href")
    except requests.RequestException:
        pass

    return None


def map_team(team_name: str) -> str:
    """ 
    Map team abbreviations to standard forms.
    """
    if team_name == "WSH":
        return "WAS"
    if team_name == "LAR":
        return "LA"
    return team_name


def get_team_details(year: int, week: int) -> List[Dict[str, Any]]:
    """
    Fetch NFL schedule details including:
    - home team abbreviation
    - away team abbreviation
    - head coach names
    - stadium
    - game ID
    - home and away team logo URLs

    Returns:
        List[Dict]: A list of game dictionaries with all details.
    """
    url = f"https://cdn.espn.com/core/nfl/schedule?xhr=1&year={year}&week={week}"
    response = requests.get(url)
    data = response.json()

    games: List[Dict[str, Any]] = []
    schedule = data.get("content", {}).get("schedule", {})

    for date_key, date_data in schedule.items():
        for game in date_data.get("games", []):
            comp = game["competitions"][0]
            teams = comp["competitors"]

            home = next((t for t in teams if t.get("homeAway") == "home"), None)
            away = next((t for t in teams if t.get("homeAway") == "away"), None)
            if not home or not away:
                continue

            home_abbr = home["team"].get("abbreviation")
            away_abbr = away["team"].get("abbreviation")
            stadium = comp.get("venue", {}).get("fullName")
            game_id = comp.get("id")

            home_id = home["team"].get("id")
            away_id = away["team"].get("id")

            home_logo = get_team_logo(home_id, year)
            away_logo = get_team_logo(away_id, year)

            home_first, home_last = get_coach_name(home_id, year)
            away_first, away_last = get_coach_name(away_id, year)

            games.append({
                "game_id": game_id,
                "home_team": map_team(home_abbr),
                "home_coach": f"{home_first or ''} {home_last or ''}".strip(),
                "home_team_logo_url": home_logo,
                "away_team": map_team(away_abbr),
                "away_coach": f"{away_first or ''} {away_last or ''}".strip(),
                "away_team_logo_url": away_logo,
                "stadium": stadium
            })

    return games


def get_match_winner(event_id: str) -> Optional[str]:
    """
    Fetch the winning team's abbreviation for a given NFL event ID from ESPN's API.
    
    Returns:
        str | None: The winner's abbreviation if found, else None
    """
    base_url = f"https://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/{event_id}"

    try:
        event_response = requests.get(base_url)
        event_data = event_response.json()

        competitions = event_data.get("competitions", [])
        if not competitions or not isinstance(competitions, list):
            return None

        competition_url = competitions[0].get("$ref")
        if not competition_url:
            return None

        competition_data = requests.get(competition_url).json()
        competitors = competition_data.get("competitors", [])
        if not competitors:
            return None

        for team_info in competitors:
            team_data = requests.get(team_info["$ref"]).json()
            if team_data.get("winner", False):
                team_url = team_data["team"]["$ref"]
                team_details = requests.get(team_url).json()
                return team_details.get("abbreviation")

    except requests.RequestException:
        pass

    return None

In [12]:
get_team_details(year = 2025, week = 1)

[{'game_id': '401772510',
  'home_team': 'PHI',
  'home_coach': 'Nick Sirianni',
  'home_team_logo_url': 'https://a.espncdn.com/i/teamlogos/nfl/500/phi.png',
  'away_team': 'DAL',
  'away_coach': 'Brian Schottenheimer',
  'away_team_logo_url': 'https://a.espncdn.com/i/teamlogos/nfl/500/dal.png',
  'stadium': 'Lincoln Financial Field'},
 {'game_id': '401772714',
  'home_team': 'LAC',
  'home_coach': 'Jim Harbaugh',
  'home_team_logo_url': 'https://a.espncdn.com/i/teamlogos/nfl/500/lac.png',
  'away_team': 'KC',
  'away_coach': 'Andy Reid',
  'away_team_logo_url': 'https://a.espncdn.com/i/teamlogos/nfl/500/kc.png',
  'stadium': 'Corinthians Arena'},
 {'game_id': '401772830',
  'home_team': 'ATL',
  'home_coach': 'Raheem Morris',
  'home_team_logo_url': 'https://a.espncdn.com/i/teamlogos/nfl/500/atl.png',
  'away_team': 'TB',
  'away_coach': 'Todd Bowles',
  'away_team_logo_url': 'https://a.espncdn.com/i/teamlogos/nfl/500/tb.png',
  'stadium': 'Mercedes-Benz Stadium'},
 {'game_id': '401772829',
  'home_team': 'CLE',
  'home_coach': 'Kevin Stefanski',
  'home_team_logo_url': 'https://a.espncdn.com/i/teamlogos/nfl/500/cle.png',
  'away_team': 'CIN',
  'away_coach': 'Zac Taylor',
  'away_team_logo_url': 'https://a.espncdn.com/i/teamlogos/nfl/500/cin.png',
  'stadium': 'Huntington Bank Field'},
 {'game_id': '401772719',
  'home_team': 'IND',
  'home_coach': 'Shane Steichen',
  'home_team_logo_url': 'https://a.espncdn.com/i/teamlogos/nfl/500/ind.png',
  'away_team': 'MIA',
  'away_coach': 'Mike McDaniel',
  'away_team_logo_url': 'https://a.espncdn.com/i/teamlogos/nfl/500/mia.png',
  'stadium': 'Lucas Oil Stadium'},
 {'game_id': '401772720',
  'home_team': 'NE',
  'home_coach': 'Mike Vrabel',
  'home_team_logo_url': 'https://a.espncdn.com/i/teamlogos/nfl/500/ne.png',
  'away_team': 'LV',
  'away_coach': 'Pete Carroll',
  'away_team_logo_url': 'https://a.espncdn.com/i/teamlogos/nfl/500/lv.png',
  'stadium': 'Gillette Stadium'},
 {'game_id': '401772718',
  'home_team': 'NO',
  'home_coach': 'Kellen Moore',
  'home_team_logo_url': 'https://a.espncdn.com/i/teamlogos/nfl/500/no.png',
  'away_team': 'ARI',
  'away_coach': 'Jonathan Gannon',
  'away_team_logo_url': 'https://a.espncdn.com/i/teamlogos/nfl/500/ari.png',
  'stadium': 'Caesars Superdome'},
 {'game_id': '401772721',
  'home_team': 'NYJ',
  'home_coach': 'Aaron Glenn',
  'home_team_logo_url': 'https://a.espncdn.com/i/teamlogos/nfl/500/nyj.png',
  'away_team': 'PIT',
  'away_coach': 'Mike Tomlin',
  'away_team_logo_url': 'https://a.espncdn.com/i/teamlogos/nfl/500/pit.png',
  'stadium': 'MetLife Stadium'},
 {'game_id': '401772827',
  'home_team': 'WAS',
  'home_coach': 'Dan Quinn',
  'home_team_logo_url': 'https://a.espncdn.com/i/teamlogos/nfl/500/wsh.png',
  'away_team': 'NYG',
  'away_coach': 'Brian Daboll',
  'away_team_logo_url': 'https://a.espncdn.com/i/teamlogos/nfl/500/nyg.png',
  'stadium': 'Northwest Stadium'},
 {'game_id': '401772828',
  'home_team': 'JAX',
  'home_coach': 'Liam Coen',
  'home_team_logo_url': 'https://a.espncdn.com/i/teamlogos/nfl/500/jax.png',
  'away_team': 'CAR',
  'away_coach': 'Dave Canales',
  'away_team_logo_url': 'https://a.espncdn.com/i/teamlogos/nfl/500/car.png',
  'stadium': 'EverBank Stadium'},
 {'game_id': '401772832',
  'home_team': 'DEN',
  'home_coach': 'Sean Payton',
  'home_team_logo_url': 'https://a.espncdn.com/i/teamlogos/nfl/500/den.png',
  'away_team': 'TEN',
  'away_coach': 'Brian Callahan',
  'away_team_logo_url': 'https://a.espncdn.com/i/teamlogos/nfl/500/ten.png',
  'stadium': 'Empower Field at Mile High'},
 {'game_id': '401772831',
  'home_team': 'SEA',
  'home_coach': 'Mike Macdonald',
  'home_team_logo_url': 'https://a.espncdn.com/i/teamlogos/nfl/500/sea.png',
  'away_team': 'SF',
  'away_coach': 'Kyle Shanahan',
  'away_team_logo_url': 'https://a.espncdn.com/i/teamlogos/nfl/500/sf.png',
  'stadium': 'Lumen Field'},
 {'game_id': '401772722',
  'home_team': 'GB',
  'home_coach': 'Matt LaFleur',
  'home_team_logo_url': 'https://a.espncdn.com/i/teamlogos/nfl/500/gb.png',
  'away_team': 'DET',
  'away_coach': 'Dan Campbell',
  'away_team_logo_url': 'https://a.espncdn.com/i/teamlogos/nfl/500/det.png',
  'stadium': 'Lambeau Field'},
 {'game_id': '401772723',
  'home_team': 'LA',
  'home_coach': 'Sean McVay',
  'home_team_logo_url': 'https://a.espncdn.com/i/teamlogos/nfl/500/lar.png',
  'away_team': 'HOU',
  'away_coach': 'DeMeco Ryans',
  'away_team_logo_url': 'https://a.espncdn.com/i/teamlogos/nfl/500/hou.png',
  'stadium': 'SoFi Stadium'},
 {'game_id': '401772918',
  'home_team': 'BUF',
  'home_coach': 'Sean McDermott',
  'home_team_logo_url': 'https://a.espncdn.com/i/teamlogos/nfl/500/buf.png',
  'away_team': 'BAL',
  'away_coach': 'John Harbaugh',
  'away_team_logo_url': 'https://a.espncdn.com/i/teamlogos/nfl/500/bal.png',
  'stadium': 'Highmark Stadium'},
 {'game_id': '401772810',
  'home_team': 'CHI',
  'home_coach': 'Ben Johnson',
  'home_team_logo_url': 'https://a.espncdn.com/i/teamlogos/nfl/500/chi.png',
  'away_team': 'MIN',
  'away_coach': "Kevin O'Connell",
  'away_team_logo_url': 'https://a.espncdn.com/i/teamlogos/nfl/500/min.png',
  'stadium': 'Soldier Field'}]

In [27]:
import requests
from typing import Optional, Dict

def get_match_scores(event_id: str) -> Optional[Dict[str, int]]:
    """
    Fetches home and away team scores for a given NFL event ID from ESPN's API.
    
    This corrected version avoids redundant API calls and correctly follows the '$ref'
    links to retrieve the final scores for each team.

    Args:
        event_id: The unique identifier for the ESPN event (e.g., "401220116").

    Returns:
        A dictionary with "home_score" and "away_score", or None if an error occurs.
        Example: {"home_score": 27, "away_score": 17}
    """
    # The primary URL for the event data
    base_url = f"https://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/{event_id}"
    
    try:
        # Step 1: Fetch the main event data in a single request.
        event_data = requests.get(base_url).json()

        # Step 2: Navigate directly to the list of competitors.
        # The structure is event -> competitions[0] -> competitors
        competitors = event_data.get("competitions", [{}])[0].get("competitors", [])

        if not competitors or len(competitors) != 2:
            print("Error: Competitors data not found or incomplete.")
            return None

        scores = {}

        # Step 3: Loop through the two competitors to get their scores.
        for competitor in competitors:
            team_side = competitor.get("homeAway")
            
            # The 'score' key contains a dictionary with a '$ref' URL to the actual score data.
            # We must fetch this URL to get the score value.
            score_ref_url = competitor.get("score", {}).get("$ref")
            
            if not team_side or not score_ref_url:
                continue # Skip if essential data is missing

            # Step 4: Fetch the score from its specific endpoint and get the 'value'.
            score_data = requests.get(score_ref_url).json()
            score_value = int(score_data.get("value", 0))

            if team_side == "home":
                scores["home_score"] = score_value
            elif team_side == "away":
                scores["away_score"] = score_value
        
        # Ensure both scores were found before returning
        if "home_score" in scores and "away_score" in scores:
            return scores
        else:
            print("Error: Could not determine both home and away scores.")
            return None

    except requests.exceptions.RequestException as e:
        print(f"Error fetching data from ESPN API: {e}")
        return None
    except (KeyError, IndexError, TypeError) as e:
        print(f"Error parsing the JSON data structure: {e}")
        return None
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
        return None

In [30]:
print(get_match_scores("401772922"))

{'home_score': 20, 'away_score': 23}

In [ ]:
import nfl_data_py as nfl

data = nfl.import_pbp_data(years = [2025])

2025 done.
Downcasting floats.

In [8]:
data[(data["week"] == 7) & (data["game_seconds_remaining"] == 0)]

,play_id,game_id,old_game_id,home_team,away_team,season_type,week,posteam,posteam_type,defteam,...,out_of_bounds,home_opening_kickoff,qb_epa,xyac_epa,xyac_mean_yardage,xyac_median_yardage,xyac_success,xyac_fd,xpass,pass_oe
16192,4562.0,2025_07_PIT_CIN,2025101600,CIN,PIT,REG,7,PIT,away,CIN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [1]:
import nflreadpy as nfl

In [16]:
data = nfl.load_pbp(2023)
data.head()

shape: (5, 372)
┌─────────┬────────────┬────────────┬───────────┬───┬────────────┬──────────┬──────────┬───────────┐
│ play_id ┆ game_id    ┆ old_game_i ┆ home_team ┆ … ┆ xyac_succe ┆ xyac_fd  ┆ xpass    ┆ pass_oe   │
│ ---     ┆ ---        ┆ d          ┆ ---       ┆   ┆ ss         ┆ ---      ┆ ---      ┆ ---       │
│ f64     ┆ str        ┆ ---        ┆ str       ┆   ┆ ---        ┆ f64      ┆ f64      ┆ f64       │
│         ┆            ┆ str        ┆           ┆   ┆ f64        ┆          ┆          ┆           │
╞═════════╪════════════╪════════════╪═══════════╪═══╪════════════╪══════════╪══════════╪═══════════╡
│ 1.0     ┆ 2023_01_AR ┆ 2023091007 ┆ WAS       ┆ … ┆ null       ┆ null     ┆ null     ┆ null      │
│         ┆ I_WAS      ┆            ┆           ┆   ┆            ┆          ┆          ┆           │
│ 39.0    ┆ 2023_01_AR ┆ 2023091007 ┆ WAS       ┆ … ┆ null       ┆ null     ┆ null     ┆ null      │
│         ┆ I_WAS      ┆            ┆           ┆   ┆            ┆          ┆          ┆           │
│ 55.0    ┆ 2023_01_AR ┆ 2023091007 ┆ WAS       ┆ … ┆ null       ┆ null     ┆ 0.515058 ┆ -51.50584 │
│         ┆ I_WAS      ┆            ┆           ┆   ┆            ┆          ┆          ┆ 6         │
│ 77.0    ┆ 2023_01_AR ┆ 2023091007 ┆ WAS       ┆ … ┆ 0.996628   ┆ 0.583928 ┆ 0.661106 ┆ 33.889407 │
│         ┆ I_WAS      ┆            ┆           ┆   ┆            ┆          ┆          ┆           │
│ 102.0   ┆ 2023_01_AR ┆ 2023091007 ┆ WAS       ┆ … ┆ null       ┆ null     ┆ 0.196065 ┆ -19.60646 │
│         ┆ I_WAS      ┆            ┆           ┆   ┆            ┆          ┆          ┆ 7         │
└─────────┴────────────┴────────────┴───────────┴───┴────────────┴──────────┴──────────┴───────────┘

In [26]:
data

shape: (49_665, 372)
┌─────────┬────────────┬────────────┬───────────┬───┬────────────┬──────────┬──────────┬───────────┐
│ play_id ┆ game_id    ┆ old_game_i ┆ home_team ┆ … ┆ xyac_succe ┆ xyac_fd  ┆ xpass    ┆ pass_oe   │
│ ---     ┆ ---        ┆ d          ┆ ---       ┆   ┆ ss         ┆ ---      ┆ ---      ┆ ---       │
│ f64     ┆ str        ┆ ---        ┆ str       ┆   ┆ ---        ┆ f64      ┆ f64      ┆ f64       │
│         ┆            ┆ str        ┆           ┆   ┆ f64        ┆          ┆          ┆           │
╞═════════╪════════════╪════════════╪═══════════╪═══╪════════════╪══════════╪══════════╪═══════════╡
│ 1.0     ┆ 2023_01_AR ┆ 2023091007 ┆ WAS       ┆ … ┆ null       ┆ null     ┆ null     ┆ null      │
│         ┆ I_WAS      ┆            ┆           ┆   ┆            ┆          ┆          ┆           │
│ 39.0    ┆ 2023_01_AR ┆ 2023091007 ┆ WAS       ┆ … ┆ null       ┆ null     ┆ null     ┆ null      │
│         ┆ I_WAS      ┆            ┆           ┆   ┆            ┆          ┆          ┆           │
│ 55.0    ┆ 2023_01_AR ┆ 2023091007 ┆ WAS       ┆ … ┆ null       ┆ null     ┆ 0.515058 ┆ -51.50584 │
│         ┆ I_WAS      ┆            ┆           ┆   ┆            ┆          ┆          ┆ 6         │
│ 77.0    ┆ 2023_01_AR ┆ 2023091007 ┆ WAS       ┆ … ┆ 0.996628   ┆ 0.583928 ┆ 0.661106 ┆ 33.889407 │
│         ┆ I_WAS      ┆            ┆           ┆   ┆            ┆          ┆          ┆           │
│ 102.0   ┆ 2023_01_AR ┆ 2023091007 ┆ WAS       ┆ … ┆ null       ┆ null     ┆ 0.196065 ┆ -19.60646 │
│         ┆ I_WAS      ┆            ┆           ┆   ┆            ┆          ┆          ┆ 7         │
│ …       ┆ …          ┆ …          ┆ …         ┆ … ┆ …          ┆ …        ┆ …        ┆ …         │
│ 4791.0  ┆ 2023_22_SF ┆ 2024021100 ┆ KC        ┆ … ┆ null       ┆ null     ┆ 0.182589 ┆ 81.741054 │
│         ┆ _KC        ┆            ┆           ┆   ┆            ┆          ┆          ┆           │
│ 4813.0  ┆ 2023_22_SF ┆ 2024021100 ┆ KC        ┆ … ┆ null       ┆ null     ┆ 0.310144 ┆ -31.01439 │
│         ┆ _KC        ┆            ┆           ┆   ┆            ┆          ┆          ┆ 8         │
│ 4835.0  ┆ 2023_22_SF ┆ 2024021100 ┆ KC        ┆ … ┆ 0.428395   ┆ 0.361828 ┆ 0.6004   ┆ 39.959973 │
│         ┆ _KC        ┆            ┆           ┆   ┆            ┆          ┆          ┆           │
│ 4860.0  ┆ 2023_22_SF ┆ 2024021100 ┆ KC        ┆ … ┆ 0.993362   ┆ 0.784198 ┆ 0.623245 ┆ 37.675518 │
│         ┆ _KC        ┆            ┆           ┆   ┆            ┆          ┆          ┆           │
│ 4881.0  ┆ 2023_22_SF ┆ 2024021100 ┆ KC        ┆ … ┆ null       ┆ null     ┆ null     ┆ null      │
│         ┆ _KC        ┆            ┆           ┆   ┆            ┆          ┆          ┆           │
└─────────┴────────────┴────────────┴───────────┴───┴────────────┴──────────┴──────────┴───────────┘